# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hansard for Historians
email: tim@discontents.com.au
description: > # this means to ignore newlines until "baseurl:"
  Commonwealth of Australia Hansard presented in an easy-to-read format for historians and other lovers of political speech.
baseurl: "/historic-hansard" # the subpath of your site, e.g. /blog
url: "http://wragge.github.io" # the base hostname & protocol for your site
collections:
  hofreps:
    output: true
    permalink: '/:collection/:path/'

defaults:
  -
    scope:
      path: ""
      type: "hofreps" # a collection in your site, in plural form
    values:
      layout: "default_day"

# Build settings
markdown: kramdown
